services:
  mongo:
    image: mongo:6
    container_name: shopmaster-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ShopMaster
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: shopmaster-app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: ShopMaster

volumes:
  mongo_data: